project_id = "sdvakfhmoaoucmhbhwvy"

[functions.admin-api]
  verify_jwt = false

[functions.start-scheduled-auctions]
  verify_jwt = false

[functions.send-notifications]
  verify_jwt = false

[functions.cleanup-old-vehicle-files]
  verify_jwt = false

[functions.cleanup-cars-history]
  verify_jwt = false

[functions.close-ended-auctions]
  verify_jwt = false

[functions.generate-audit-report]
  verify_jwt = false

[functions.recover-auction]
  verify_jwt = false

[functions.reset-auction-system]
  verify_jwt = false
