
project_id = "sdvakfhmoaoucmhbhwvy"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true
port = 54325

[analytics]
enabled = true
port = 54327

[realtime]
enabled = true

[functions.process-auction-results]
verify_jwt = true
