-- Create a secure function to fetch cars with seller email information
CREATE OR REPLACE FUNCTION get_cars_with_seller_info()
RETURNS TABLE (
  id uuid,
  seller_id uuid,
  make text,
  model text,
  year integer,
  mileage numeric,
  vin text,
  transmission text,
  reserve_price numeric,
  title text,
  seller_name text,
  street_address text,
  town text,
  postcode text,
  county text,
  mobile_number text,
  features jsonb,
  status text,
  created_at timestamptz,
  updated_at timestamptz,
  is_damaged boolean,
  is_registered_in_poland boolean,
  has_private_plate boolean,
  finance_amount numeric,
  service_history_type text,
  seat_material text,
  number_of_keys integer,
  seller_notes text,
  additional_photos jsonb,
  required_photos jsonb,
  rim_photos jsonb,
  form_metadata jsonb,
  valuation_data jsonb,
  fuel_type text,
  images text[],
  auction_status text,
  email_notification_sent boolean,
  auction_scheduled boolean,
  awaiting_seller_decision boolean,
  last_saved timestamptz,
  has_service_history boolean,
  is_manually_controlled boolean,
  current_bid numeric,
  minimum_bid_increment numeric,
  auction_end_time timestamptz,
  is_auction boolean,
  registration_number text,
  seller_email text
) 
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  RETURN QUERY
  SELECT 
    c.id,
    c.seller_id,
    c.make,
    c.model,
    c.year,
    c.mileage,
    c.vin,
    c.transmission,
    c.reserve_price,
    c.title,
    c.seller_name,
    c.street_address,
    c.town,
    c.postcode,
    c.county,
    c.mobile_number,
    c.features,
    c.status,
    c.created_at,
    c.updated_at,
    c.is_damaged,
    c.is_registered_in_poland,
    c.has_private_plate,
    c.finance_amount,
    c.service_history_type,
    c.seat_material,
    c.number_of_keys,
    c.seller_notes,
    c.additional_photos,
    c.required_photos,
    c.rim_photos,
    c.form_metadata,
    c.valuation_data,
    c.fuel_type,
    c.images,
    c.auction_status,
    c.email_notification_sent,
    c.auction_scheduled,
    c.awaiting_seller_decision,
    c.last_saved,
    c.has_service_history,
    c.is_manually_controlled,
    c.current_bid,
    c.minimum_bid_increment,
    c.auction_end_time,
    c.is_auction,
    c.registration_number,
    u.email as seller_email
  FROM cars c
  LEFT JOIN auth.users u ON c.seller_id = u.id
  ORDER BY c.created_at DESC;
END;
$$ LANGUAGE plpgsql;