
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sdvakfhmoaoucmhbhwvy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNkdmFrZmhtb2FvdWNtaGJod3Z5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ3OTI1OTEsImV4cCI6MjA1MDM2ODU5MX0.wvvxbqF3Hg_fmQ_4aJCqISQvcFXhm-2BngjvO6EHL0M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Extend the client type to include our custom RPC functions
declare module '@supabase/supabase-js' {
  interface SupabaseClient {
    rpc<R>(
      fn: 'approve_listing' | 'reject_listing' | 'verify_dealer' | 'reject_dealer' | 'admin_end_auction' | 'authenticate_dealer' | 'calculate_reserve_price' | 'calculate_reserve_price_from_min_med' | 'check_email_exists' | 'close_ended_auctions' | 'create_dealer_with_profile' | 'debug_auth_user_id' | 'debug_dealer_access' | 'get_dealer_by_user_id' | 'get_user_id_by_email' | 'is_admin' | 'log_admin_action' | 'place_bid' | 'verify_password' | 'test_admin_access' | 'debug_admin_context' | 'get_email_notification_counts' | 'get_admin_notifications' | 'mark_notification_read' | 'mark_all_notifications_read' | 'get_form_tracking_logs' | 'get_activity_logs',
      params?: object,
      options?: object
    ): Promise<{
      data: R;
      error: Error | null;
    }>;
  }
}
